version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.16.2

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - run:
          name: Run tests
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
