name: Test & Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test-build:
    name: Run tests and build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
